<?php

namespace ContainerKT4W6BM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PurchaseController' shared autowired service.
     *
     * @return \App\Controller\PurchaseController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\framework-bundle\\Controller\\AbstractController.php';
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\PurchaseController.php';

        $container->services['App\\Controller\\PurchaseController'] = $instance = new \App\Controller\PurchaseController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\PurchaseController', $container));

        return $instance;
    }
}
