<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKT4W6BM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKT4W6BM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKT4W6BM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKT4W6BM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKT4W6BM\App_KernelDevDebugContainer([
    'container.build_hash' => 'KT4W6BM',
    'container.build_id' => '4ee9484e',
    'container.build_time' => 1600961947,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKT4W6BM');
