<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'client' => [[], ['_controller' => 'App\\Controller\\ClientController::saveData'], [], [['text', '/client/save']], [], []],
    'purchase' => [[], ['_controller' => 'App\\Controller\\PurchaseController::saveData'], [], [['text', '/purchase/save']], [], []],
];
